### ISSUE TITLE
Blackbox

### ISSUE THREAD

**Issue by DaanWet** [DaanWet/Pingo_Discord_Bot#29]
Vraag stellen via bot, antwoorden direct verwijderen (of dm'n naar bot) en dan opt einde alle antwoorden anoniem opvragen

**Comment by Zelzahn** [comment]
Antwoorden direct verwijderen is niet direct een optie, aangezien mensen wel nog steeds de notificatie zullen krijgen.

**Comment by DaanWet** [comment]
Ja da dacht ik ook
