### ISSUE TITLE
Gender neutral / inclusive pronouns

### ISSUE THREAD

**Issue by Miningflo** [DaanWet/Pingo_Discord_Bot#32]
https://github.com/DaanWet/Pingo_Discord_Bot/blob/80d1cbc3b48d393f05afe7ef2a687143849034ec/src/main/java/commands/casino/uno/Play.java#L73

Please use they/them

**Comment by Zelzahn** [comment]
Maybe a different formatting could be used such that pronouns aren't needed?

**Comment by Miningflo** [comment]
> Maybe a different formatting could be used such that pronouns aren't needed?

This is not possible when referring to a person, unless you want to go like: "x credits were won by the winner of this game"

**Comment by Zelzahn** [comment]
I was thinking something similar to this:
> X played a Y and won. Z credits have been won.
Or:
> X played aY and won Z credits.

**Comment by Miningflo** [comment]
> I was thinking something similar to this:
> 
> > X played a Y and won. Z credits have been won.
> 
> Or:
> 
> > X played aY and won Z credits.

X played a game of Y and won. Z credits have been awarded.
