### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by Zelzahn** [DaanWet/Pingo_Discord_Bot#34]

**Comment by DaanWet** [comment]
Explain, Discord doesn't work that way

**Comment by Zelzahn** [comment]
One possiblity would be to use a setting which controls the language / locale of the bot. Furthermore the bot could use ResourceBundles and an [Locale](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html) object to easily set the language.

I don't know if this is scaleable to multiple guilds though.
