### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Doom306** [DaanWet/Pingo_Discord_Bot#46]
Can you give me the files for [this](https://github.com/DaanWet/Pingo_Discord_Bot/blob/531a19fc4ec17c06df98d608a226bef8004ca224/src/main/java/utils/ImageHandler.java#L15) . Thanks!!!

**Comment by Zelzahn** [comment]
Hey can you please not close and reopen issues to bump them?

**Comment by Doom306** [comment]
Oh ok sorry
