### ISSUE TITLE
Add custom betting

### ISSUE THREAD

**Issue by DaanWet** [DaanWet/Pingo_Discord_Bot#58]
Make a command that starts a question/custom bet, users can bet on the answer by replying to the message with `!bet amount "answer"`
The correct answers can then be selected by using `!endbet @someone`
Disabled when betting is disabled on the server

**Comment by Zelzahn** [comment]
This could be further split up in open questions and multiple choice questions. Multiple choice in particular could feature automatic resolving and pretty print of the options.
