### ISSUE TITLE
Blackjack game breaks permanently for user during high latency

### ISSUE THREAD

**Issue by Jotra04** [DaanWet/Pingo_Discord_Bot#93]
Using the !bj command during a high latency period may cause a user to start a game without receiving the game message:

This causes the following situation:
```
> !bj 10
< You're already playing a game

> !stand
< Oops, something went wrong: Cannot invoke "java.lang.Long.longValue()" because the return value of "companions.cardgames.BlackJackGame.getMessageId()" is null
```

This permanently locks the user out of playing Blackjack

**Comment by DaanWet** [comment]
This is a duplicate of #55
